name: Design change
description: Formalize an approved design update backed by docs and prior discussion.
labels:
  - design
  - planning
body:
  - type: markdown
    attributes:
      value: |
        Use this template once a feature proposal or discovery work is ready to become a concrete design change. Link to supporting docs and the originating proposal when available.
  - type: textarea
    id: problem
    attributes:
      label: Problem / Context
      description: What problem are we solving? Why now?
      placeholder: Clear description of the problem and context
    validations:
      required: true
  - type: input
    id: proposal_link
    attributes:
      label: Related proposal
      description: Link to the originating feature proposal issue, if one exists.
      placeholder: "#123"
  - type: input
    id: design_link
    attributes:
      label: Design docs
      description: Link to requirements, architecture docs, ADRs, or PRs updating them.
      placeholder: docs/design/... (or a PR adding them)
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Bullet points of outcomes that must be true
      placeholder: "- …"
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Notes / References
      description: Extra links, ADRs, diagrams, or implementation considerations
