name: example-node-ci

# Intent: Example Node/TypeScript CI workflow. This file is under 'examples/' to avoid
# running by default. To enable, move it to '.github/workflows/node-ci.yml'.

on:
  workflow_dispatch:

jobs:
  node-ci:
    name: Node/TS Lint/Format/Typecheck/Smoke
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Detect Node project
        id: detect
        run: |
          if [ -f package.json ]; then
            echo "has_node=true" >> $GITHUB_OUTPUT
          else
            echo "has_node=false" >> $GITHUB_OUTPUT
          fi

      - uses: actions/setup-node@v4
        if: steps.detect.outputs.has_node == 'true'
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install
        if: steps.detect.outputs.has_node == 'true'
        run: |
          npm ci --prefer-offline --no-audit --fund=false || npm install

      - name: Lint (eslint)
        if: steps.detect.outputs.has_node == 'true'
        run: |
          npx --yes eslint . || echo "eslint not configured; skipping."

      - name: Format check (prettier)
        if: steps.detect.outputs.has_node == 'true'
        run: |
          npx --yes prettier --check . || echo "prettier not configured; skipping."

      - name: Type check (tsc)
        if: steps.detect.outputs.has_node == 'true'
        run: |
          if [ -f tsconfig.json ]; then
            npx --yes tsc --noEmit
          else
            echo "No tsconfig.json; assuming JS project."
          fi

      - name: Test (npm test)
        if: steps.detect.outputs.has_node == 'true'
        run: |
          if npm run | grep -q " test"; then
            npm test --silent
          else
            echo "No test script; skipping."
          fi

