name: example-python-ci

# Intent: Example Python CI workflow. This file is under 'examples/' to avoid
# running by default. To enable, move it to '.github/workflows/python-ci.yml'.

on:
  workflow_dispatch:

jobs:
  python-ci:
    name: Python Lint/Format/Smoke
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Detect Python project
        id: detect
        run: |
          if ls pyproject.toml setup.cfg setup.py requirements*.txt >/dev/null 2>&1; then
            echo "has_python=true" >> $GITHUB_OUTPUT
          else
            echo "has_python=false" >> $GITHUB_OUTPUT
          fi

      - uses: actions/setup-python@v5
        if: steps.detect.outputs.has_python == 'true'
        with:
          python-version: '3.12'

      - name: Install tooling (ruff/black/pytest)
        if: steps.detect.outputs.has_python == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install ruff black pytest

      - name: Lint (ruff)
        if: steps.detect.outputs.has_python == 'true'
        run: ruff check .

      - name: Format check (black)
        if: steps.detect.outputs.has_python == 'true'
        run: black --check .

      - name: Byte-compile scripts (tools)
        if: steps.detect.outputs.has_python == 'true'
        run: |
          if compgen -G "tools/*.py" > /dev/null; then
            python -m py_compile tools/*.py
          else
            echo "No Python tools to byte-compile."
          fi

      - name: Test (pytest smoke)
        if: steps.detect.outputs.has_python == 'true'
        run: |
          if [ -d tests ] || ls test_*.py *_test.py >/dev/null 2>&1; then
            pytest -q
          else
            echo "No tests discovered; skipping."
          fi
