name: CLI Smoke Test

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Byte-compile tools
        run: python -m py_compile tools/*.py
      - name: CLI --help
        run: python tools/ai_contract_cli.py --help
