name: pre-commit

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit gitlint
      - name: Run pre-commit on all files
        run: pre-commit run --all-files --show-diff-on-failure
