# .github/workflows/python-scripts-smoke.yml
name: python-scripts-smoke
on: [pull_request, push]
jobs:
  py-compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Byte-compile tools
        run: python -m py_compile tools/*.py
