# Instance workflow for pvliesdonk/ai_engineer_contract; adjust for your repository.
name: release-please
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure release token is configured
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
        run: |
          if [ -z "$RELEASE_TOKEN" ]; then
            echo "RELEASE_PLEASE_TOKEN secret is not configured. Please add a PAT/App token with contents:write (repo scope)." >&2
            exit 1
          fi
      - uses: googleapis/release-please-action@v4
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
