name: release-please
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          command: manifest
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json

